server:
  port: 8082
spring:
  application:
    name: seckill-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/seckill
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
rocketmq:
  name-server: 192.168.213.128:9876
  consumer:
    group: seckill-consumer-group

